import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const suit = localFont({
  src: "../public/fonts/SUIT-Variable.woff2",
  variable: "--font-suit",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${suit.variable} h-full bg-gray-100`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-full text-gray-900 antialiased`}
      >
        <div className="flex h-full min-h-screen items-stretch justify-center">
          <div className="relative flex h-full w-full max-w-[768px] flex-col bg-white shadow-md">
            {/* 헤더자리 */}
            <header className="h-[44px] flex-none items-center bg-red-100 text-center">
              deafult ui
            </header>
            <main className="flex-1 overflow-y-auto">{children}</main>
            {/* 바텀자리 */}
            {/* <footer className="flex-none">푸터</footer> */}
          </div>
        </div>
      </body>
    </html>
  );
}
