import type { Metadata } from "next";

import "./globals.css";
import { QueryProvider } from "@/src/app/providers/queryProvider";
import { BottomNavigation } from "@/src/shared/ui/bottomNavigation/";
import { Toast } from "@/src/shared/ui/toast";
import GlobalRender from "@/src/shared/ui/globalRender/globalRender";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="h-full bg-gray-100">
      <body className="h-full bg-white text-gray-900 antialiased">
        <QueryProvider>
          <div className="flex min-h-screen w-full items-stretch">
            {/* <div className="relative flex h-full w-full max-w-[768px] flex-col bg-white shadow-md"> */}
            <div className="relative flex min-h-screen w-full flex-col bg-transparent shadow-none">
              {/* 헤더자리 */}
              {/* <header className="flex h-[44px] w-full items-center"></header> */}
              {/* <TempHeaders className="h-full w-full" /> */}
              <GlobalRender>{children}</GlobalRender>
              <BottomNavigation />
            </div>
          </div>
          <Toast />
        </QueryProvider>
      </body>
    </html>
  );
}
