import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { QueryProvider } from "@/src/app/providers/queryProvider";
import { TempHeaders } from "@/src/assets/images/common/header";
import { BottomNavigation } from "@/src/shared/ui/bottomNavigation/";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const suit = localFont({
  src: "../public/fonts/SUIT-Variable.woff2",
  variable: "--font-suit",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${suit.variable} h-full bg-gray-100`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-full text-gray-900 antialiased`}
      >
        <QueryProvider>
          <div className="flex h-full min-h-screen items-stretch justify-center pt-5">
            <div className="relative flex h-full w-full max-w-[768px] flex-col bg-white shadow-md">
              {/* 헤더자리 */}
              {/* <header className="flex h-[44px] w-full items-center"></header> */}
              {/* <TempHeaders className="h-full w-full" /> */}

              <main className="flex-1 overflow-y-auto">{children}</main>
              <BottomNavigation />
            </div>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
